### ISSUE TITLE
publication of summarizer/pre-trained model

### ISSUE THREAD

**Issue by suchanun** [nakhunchumpolsathien/TR-TPBS#2]
Hi,

Are you planing to share the pre-trained model/training code or a ready-to-use summarizer in the future?

Thank you ka.

**Comment by nakhunchumpolsathien** [comment]
Hello @suchanun, thank you for reaching out. 

We do not plan to make our experimental pre-trained models available publicly any soon. For training codes, however, are available at https://github.com/nlpyang/PreSumm. If you would like to train Thai text summarization dataset on BertSum models, you need different preprocessing approach to process Thai text before feeding it as the input to BertSum models. 

Best.
