### ISSUE TITLE
Another Possible Datasource: The Momentum

### ISSUE THREAD

**Issue by heytitle** [nakhunchumpolsathien/TR-TPBS#3]
Hi,

In case you're not aware of, I've just noticed that the momentum.co also provides a summary for each article.

https://themomentum.co/junichiro-tanizaki/

It might be another good datasource that we can extend the dataset.

**Comment by nakhunchumpolsathien** [comment]
Hello, thanks for reaching out.

The-momentum is one of many websites that we plan to crawl. We actually plan to create a large-scale Thai news dataset, not soon, but yeah we do have plan to do so. 

Best.
